### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by torbenm** [torbenm/ng2-currency#1]
- [x] add demo to github pages
- [x] extend readme to include more info on the currency pipe
- [x] extend readme to include input
